name: Build Release APK
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          java-version: 8
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8

      - name: Build
        run: |
          ionic cordova build android --prod
